FROM php:7.2-cli-alpine3.7

MAINTAINER Deise Claudino

COPY . /var/www
WORKDIR /var/www


//Docker-compose.yml
//  command: ash -lex -c "php composer.phar install --no-interaction --no-suggest --verbose && php -S 0.0.0.0:80 -t /var/www/public /var/www/public/index.php"
